### ISSUE TITLE
feature request: self advertise this app in the report text

### ISSUE THREAD

**Issue by TP75** [nextcloud/issuetemplate#156]
This is a quite helpful tool.  My sincere thanks to @juliushaertl 

IMHO the idea of a self advertising text at to the bottom of the report text may be worth some additional coding efforts.

## Proposed feature:

Add a final line to any report produced such as:

```
This report was produced by help of the [issuetemplate: 0.5.0 app](https://apps.nextcloud.com/apps/issuetemplate).
```

This report was produced by help of the [issuetemplate: 0.5.0 app](https://apps.nextcloud.com/apps/issuetemplate).

**Comment by e-alfred** [comment]
I think this app should be part of the official Nextcloud release and shipped with it too by default. In essence it could help everybody getting better bug reports having all the necessary information while making bug reports and feature requests for users more easy.

**Comment by juliushaertl** [comment]
I'm not a big fan of adding more and more apps to the release as this makes updating them much harder, since they are then bound to the server release cycle.

Not sure about the note though, since when you have to parse all the information as a maintainer every line that isn't essential to the bug report might distract.

**Comment by TP75** [comment]
> I'm not a big fan of adding more and more apps to the release as this makes updating them much harder, since they are then bound to the server release cycle.

Good point. I would agree and would appreciate a minimal number of apps.

**Comment by TP75** [comment]
> Not sure about the note though, since when you have to parse all the information as a maintainer every line that isn't essential to the bug report might distract from what is actually important.

Personally I am neutral on that. Not my business and not my product, your marketing and your money. 

I can happily live without. Furthermore, I have no responsibilities with Nextcloud or burden as a payed dev in the preumed need of asking for more information in e.g., too much, too brief or lazy comments and/or problem reports.

**Comment by juliushaertl** [comment]
We advertise the issue template app in the bug report template already. Unfortunately lots of people still don't read that and skip adding the required information.

![image](https://user-images.githubusercontent.com/3404133/67208244-6eaf8d00-f415-11e9-8375-9db066ac7b4e.png)

Let's close this then for above mentioned reasons. Thanks for the suggestion anyway. It is highly appreciated :wink:
