### ISSUE TITLE
Release for Nextcloud 17?

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/issuetemplate#159]
Hello,

@juliushaertl can you publish a new release for Nextcloud 17 to the App Store? 

Do you think this app could become an official app shipped with Nextcloud directly? I am sure this app could help you and everyone developing Nextcloud apps getting better bug reports after all.

**Comment by juliushaertl** [comment]
Ah yes, totally forgot that.

**Comment by e-alfred** [comment]
@juliushaertl Can you push a new release? Nextcloud 17 is out now for a few weeks already.

**Comment by juliushaertl** [comment]
Release for 17/18 is published
