### ISSUE TITLE
nc 17.0.2 caldav broken under php7.4; works fine under php7.3

### ISSUE THREAD

**Issue by ahtoagah** [nextcloud/issuetemplate#180]
Upgrading my apache2 server to use php7.4 breaks my calendar sync which previously worked fine with php7.3.

Details:
-- nc 17.0.2 on Ubuntu 18.04.1
-- php7.4 includes all the equivalent modules as used under php7.3
-- my nc Calendar app is the most current version
-- the nc Security & Setup Warnings page shows no errors
-- on macOS 10.13.6, I setup a Caldav account to my nc server and had no problems syncing mac and nc when the servers uses php7.3
-- but when I switch my apache2 to use php7.4 it immediately breaks the calendar sync; note: only the php version is toggled, everything else remains untouched.

nc server:
Ubuntu Linux 18.04.1
Apache/2.4.29
mysql 5.7.28
php 7.3.13-1 [calendar sync works fine]
php 7.4.1 [breaks calendar sync]

nc client:
macOS 10.13.6 (High Sierra)
Calendar (for macOS) Version 10.0 (2195.4.3)

I can find nothing in the standard nc or apache2 log files which seems to show anything relevant. Are there other log files I should look into?
On macOS the Console shows some errors in lines which reference the nc "remote.php" url, but it's so cryptic I can't tell if it's relevant to the problem or "normal".

Suggestions for other things to try? Thanks.

**Comment by juliushaertl** [comment]
This is the bug tracker of the issuetemplate app. Please report server bugs in the server repo. Nextcloud 17 is not officially supporting PHP 7.4, you might need to stick with 7.3 until Nextcloud 18 is out.
