### ISSUE TITLE
Allow apps to customize the issue template

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/issuetemplate#23]
Apps should be able to register their own sections/fields to be included in the issue template.

**Comment by xraMsamohT** [comment]
Apps should have the ability to opt out of this template and use their own, if available. But this is a separate issue, right?

**Comment by juliushaertl** [comment]
Fixed with #19 

@xraMsamohT Also possible now, see: https://github.com/nextcloud/issuetemplate#integration-for-app-developers

**Comment by xraMsamohT** [comment]
@juliushaertl This is not the same as an own template. ;-)

**Comment by juliushaertl** [comment]
@xraMsamohT Might be a good idea to open an new issue for that then, since I'm not sure if i get you correctly. 😉 Since you can have your own template by removing the default ones and providing custom information.

**Comment by Rello** [comment]
hello @juliushaertl ,
i am not completely sure on how to integrate the own template.
where would I need to add the `$dispatcher->addListener('\OCA\IssueTemplate::queryAppDetails` ?
in our appinfo/app.php?

thank you for this nice feature...

**Comment by juliushaertl** [comment]
@Rello Yes, that is basically how it works. Consider moving the code to some other point, to make it a bit cleaner, as described here: https://github.com/nextcloud/documentation/blob/master/developer_manual/app/init.rst#best-practice A separate class for constructing your app details might also make sense, depending on how much you want to add.
