### ISSUE TITLE
Make NC19 compatible

### ISSUE THREAD

**Issue by szaimen** [nextcloud/issuetemplate#232]
Hi, would be great if the app would become NC19 compatible.
Thanks!

**Comment by e-alfred** [comment]
The app works fine on Nextcloud 19, @juliushaertl can you publish a new release to the App Store?

**Comment by stratege1401** [comment]
Manually edited on my testing bed ! Working fine !

A release is needed in APP store for my customers integration, please!

**Comment by szaimen** [comment]
I guess this can be closed since there was a new update with compatibility to NC19.

**Comment by stratege1401** [comment]
issue is NOT FIXED !!! Don't close stuff NOT FIXED ... unless the devell clearly announce it is dead !!!
