### ISSUE TITLE
deleted or renamed folders show up

### ISSUE THREAD

**Issue by uschlaak** [nextcloud/issuetemplate#28]
we use nextcloud with about 10 root folders including subfolders and about 10 users with explicit permissions to different root folders. The users connect to nextcloud over web and over nextcloud app for windows.

if a user deletes or renames subfolders it often happens, that the deleted folder is still showing up in web, sometimes in nextcloud app also. these folders are not showing up for all users.
If the user clicks on the deleted folder in web he gets back to the root.

We could partly solve the issue by deleting and recreating the user, but this is no solution as it happens again.

Is someone also facing the issue described above or is having an idea about how to fix it?

Thanks

Ulf

**Comment by juliushaertl** [comment]
@uschlaak This repo is just for the issuetemplate app. Please report the issue at the server repo: https://github.com/nextcloud/server
