### ISSUE TITLE
MacOS Finder Extension not working any more

### ISSUE THREAD

**Issue by djquazzi** [nextcloud/issuetemplate#38]
### Steps to reproduce
1. Disabled / re-enabled extension in System Preferences
2. Reinstalled MacOS app
3. Restarted machine

### Expected behaviour

Right clinking a file in the Finder displays Nextcloud options (Sharing)

### Actual behaviour

Nextcloud options do not appear.

Found in log:

Jan 31 08:55:27 daniel com.apple.xpc.launchd[1] (com.nextcloud.desktopclient.1440[334]): Service exited due to signal: Terminated: 15 sent by killall[706]

MacOS High Sierra 10.13.3
MacOS Nextcloud desktop app v. 2.3.3 (build 84)

**Comment by juliushaertl** [comment]
Please report this issue at the client repo https://github.com/nextcloud/client. This repository is just for the issuetemplate app. :wink:
