### ISSUE TITLE
Protect Nextcloud Server-Domain (sensitive content)

### ISSUE THREAD

**Issue by mr-bolle** [nextcloud/issuetemplate#45]
Hi, 

thank you for this usefull Application.
To protect the Server from the Issue Reporter, i would suggest set this Value also to sensitive content.

Config report > config.php
* "trusted_domains"
* "overwrite.cli.url"

br mr-bolle

**Comment by juliushaertl** [comment]
Thanks for your report. This is already tracked in https://github.com/nextcloud/issuetemplate/issues/27 so I'm closing this as a duplicate.
