### ISSUE TITLE
Release version compatible with Nextcloud 15

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/issuetemplate#49]

**Comment by enoch85** [comment]
JFTR, I didn't test it with 15, just raised the version.

**Comment by enoch85** [comment]
@juliushaertl Anything specific you want me to test? I can upgrade one of my servers and try it out.

**Comment by enoch85** [comment]
OK so I tested it and it seems like some CSP is blocking:

**Browser console**

```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).
issuetemplate:1:1
JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).
build.js:11190:11
XML Parsing Error: not well-formed
Location: https://192.168.100.36/core/fonts/Nunito-Regular.woff2
Line Number 1, Column 5: Nunito-Regular.woff2:1:5
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: https://192.168.100.36/apps/issuetemplate/js/build/build.js?v=824ae22c-0
Source Map URL: build.js.map[Learn More]
```

**Comment by juliushaertl** [comment]
Thanks for testing. I'll look into this one.

**Comment by pieter-groeneweg** [comment]
Can you update? It still shows upto version 14, not 15 yet..

**Comment by jcklpe** [comment]
I just removed it and then tried to download and enable and it didn't work for me.

**Comment by e-alfred** [comment]
It would be great to have this app back up and running to help people write more informative and verbose bug reports.

**Comment by caugner** [comment]
@juliushaertl Is there anything left to fix before releasing the NC15 version?

**Comment by juliushaertl** [comment]
0.5.0 has been released with 15/16 support
