### ISSUE TITLE
Error	PHP	Undefined index: log-detail at /var/www/html/nextcloud/apps/issuetemplate/lib/Detail.php#59

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/issuetemplate#61]
Steps to reproduce
whenever i do enable the Issuetemplate App

Expected behaviour
no php-error in the nextcloud.log

Actual behaviour

There are PHP-Errors

Server configuration detail
Operating system: Linux 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64
Webserver: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.1.25 (apache2handler)
Database: mysql 5.5.60
PHP version:
7.1.25
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, apcu, bcmath, bz2, calendar, ctype, curl, dba, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, ldap, exif, mcrypt, mysqli, PDO, pdo_mysql, pdo_sqlite, Phar, posix, redis, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, wddx, xmlreader, xmlwriter, xsl, memcached, zip, Zend OPcache
Nextcloud version: 14.0.6 - 14.0.6.0
Updated from an older Nextcloud/ownCloud or fresh install: Upgrade from 14.0.4 - 14.0.6.0, 
Where did you install Nextcloud from: Origine Source
Signing status
List of activated apps
Configuration (config/config.php)
Are you using external storage, if yes which one: no
Are you using encryption:
Are you using an external user-backend, if yes which one: no
Client configuration
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Operating system: Windows 10
Logs

{"reqId":"XFTaHGMmrzHTrK2cRVdtrQAAAAs","level":3,"time":"2019-02-02T00:45:32+01:00","remoteAddr":"xxxxx","user":"admin","app":"PHP","method":"POST","url":"\/apps\/issuetemplate\/render","message":"Undefined index: log-detail at \/var\/www\/html\/nextcloud\/apps\/issuetemplate\/lib\/Detail.php#59","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/71.0.3578.98 Safari\/537.36","version":"14.0.6.0"}
{"reqId":"XFTaHGMmrzHTrK2cRVdtrQAAAAs","level":3,"time":"2019-02-02T00:45:32+01:00","remoteAddr":"xxxxxx","user":"admin","app":"PHP","method":"POST","url":"\/apps\/issuetemplate\/render","message":"Undefined index: log-detail at \/var\/www\/html\/nextcloud\/apps\/issuetemplate\/lib\/Detail.php#59","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/71.0.3578.98 Safari\/537.36","version":"14.0.6.0"}
{"reqId":"XFTaJm4mWcbbcPLP83eFBgAAAAk","level":3,"time":"2019-02-02T00:45:42+01:00","remoteAddr":"xxxxxxx","user":"admin","app":"PHP","method":"POST","url":"\/apps\/issuetemplate\/render","message":"Undefined index: log-detail at \/var\/www\/html\/nextcloud\/apps\/issuetemplate\/lib\/Detail.php#59","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Geck

**Comment by Githopp192** [comment]
now .. did the NC Upgrade from 14.0.6 to 15.0.4 .. 

Could not download app issuetemplate .. is the not supported anymore in NC 15.0.x ?

**Comment by juliushaertl** [comment]
Should be fixed with 0.5.0
