### ISSUE TITLE
IssueTemplate Nextcloud 15

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/issuetemplate#65]
Hi Julius .. is IssueTemplate not supported anymore in Nextcloud 15 ?
Cheers
Mike

**Comment by juliushaertl** [comment]
Hi @Githopp192 Sorry, I haven't found time to release a new version yet, but it is on my todo list. Closing this as a duplicate of https://github.com/nextcloud/issuetemplate/issues/49
